# Generated by Django 5.1.6 on 2025-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Película'), ('series', 'Serie'), ('book', 'Libro')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('documentary', 'Documentary')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='note',
            field=models.CharField(max_length=300),
        ),
    ]
